100.get-started=Get started
  10.overview=Overview
  50.use-seekdb-with-sdk=SDK
  100.use-seekdb-with-sql=SQL
  200.ai-coding=Using seekdb with AI coding tools
200.develop=Develop
  10.overview=Overview
  50.ai-workflow=AI workflow
  100.connect-to-seekdb=Connect to seekdb
    200.use-client-connect-seekdb=Connect via client
    300.sample-program=Connect via drivers or ORM
      100.java=Java
      200.python=Python
      300.c=C
      400.go=Go
      500.php=PHP
      600.rust=Rust
      700.ruby=Ruby
    400.use-the-database-connection-pool=Use connection pool
  200.design-database-schema=Design database schema
    35.multi-model=Multi-model data
      100.json=JSON data
      200.spatial=Spatial data
      300.char-and-text=Character and text data
  300.read-and-write-data=Data write and read
    100.write-data=Write data
    200.read-data=Read data
      200.multi-table-join-query=Join tables
      300.use-operators-and-functions-in-query=Use operators and functions in queries
  400.llm=LLM
  500.vector-embedding=Vector embedding
  600.search=Search
    300.vector-search=Vector search
      200.vector-index=Vector index
        300.dense-vector-index=Dense vector index
        400.sparse-vector-index=Sparse vector index
      700.vector-search-reference=Reference guide
        900.vector-search-supported-clients-and-languages=Supported clients and languages
    200.hybrid-search=Hybrid search
  700.ai-function=AI functions
300.integrations=Integrations
  100.frameworks=Frameworks
  200.model-platforms=Model platforms
  300.developer-tools=Developer tools
  400.workflows=Workflows
  500.data-analyst=Data analyst
  600.mcp=MCP
  650.plugin=Plugin
  700.others=Others
400.guides=Guides
  400.deploy=Deploy seekdb
    500.environment-and-configuration-checks=Pre-deployment preparation
    700.server-mode=Server mode
  500.manage=Manage
    100.configuration-management=Configuration management
      200.system-configuration-items=Configuration items
      300.system-variable=System variables
    200.high-availability=High availability
	200.recyclebin=Recyclebin
    300.security=Security and permissions
      200.identification-and-authentication=Identification and authentication
      300.access-control=Access control
        200.user-and-permission=User and permissions
          340.role-management=Role management
      400.data-transfer-encryption=Data transmission encrption
  1000.obshell=obshell
    300.obshell-clients=obshell commands
    350.obshell-dashboard=obshell Dashboard
  1050.data-load-and-dump=Data load and dump
  1100.performance-test=Performance test
    100.vectordbbench-test-on-seekdb=Vectordbbench
    200.sysbench-test-on-seekdb=Sysbench
    300.tpc-h-test-on-seekdb=TPC-H
    400.mldr-test-on-seekdb=MLDR
450.reference=Reference
  100.mysql-compatibility=Compatibility
  200.sql=SQL reference
    100.sql-syntax=SQL syntax
      100.basic-elements=Basic elements
        100.data-type=Data types
          200.numeric=Numeric types
          300.date-and-time-types=Datetime types
          400.string=String types
          500.large-object=Large objects and text types
          800.json-formatted-data-type=JSON data types
          900.spatial-data-type=Spatial data types
          1000.roaring-bitmap-data-type=Roaring bitmap types
          1200.array-data-type=Array data types
          1300.map-data-type=Map data types
        200.expression=Expressions
        300.character-set-and-collation=Character set and collation
        400.literal=Literals
      200.operator=Operators
      400.functions=Functions
        200.single-row-functions=Single-row functions
          100.date-and-time-functions=Datetime functions
          200.string-functions=String functions
          300.conversion-functions=Conversion functions
          400.mathematical-functions=Mathematical functions
          500.comparison-functions=Comparison functions
          600.process-control-functions=Process control functions
        300.aggregate-function=Aggregate functions
        400.analysis-functions=Analysis functions
        500.encryption-and-compression-functions=Encryption functions
        600.information-functions=Information functions
        700.json-functions=JSON functions
          100.create-json-text-function=Functions for creating JSON text
          200.search-json-text-function=Functions for searching JSON text
          300.modify-json-text-function=Functions for modifying JSON text
          400.return-json-text-property-function=Functions for returning JSON text properties
          500.json-utility-function=JSON utility functions
          600.json-aggregate-function=JSON aggregate functions
          700.json-schema-function=JSON schema validation functions
        750.xml-functions=XML functions
          300.querying-xmltype-data-functions=Functions for querying XML data
          400.modify-xmltype-data-functions=Functions for modifying XML data
        800.spatial-functions=Spatial functions
        900.performance-schema=Performance schema functions
        920.lock-functions=Lock functions
        940.roaring-bitmap-functions=Bitmap functions
        950.array-functions=Array functions
        960.text-processing-functions=Text processing functions
        980.map-functions=Map functions
        990.sequence-function=Sequence function
        1000.other-functions=Other functions
      500.queries-and-subqueries=Queries and subqueries
      600.sql-statement=SQL statements
        300.alter-system=ALTER SYSTEM
        8100.select=SELECT
      700.ddl-function=DDL feature
      800.overview-of-pseudo-columns=Pseudo columns
    300.pl=PL reference
      100.what-is-pl=What is PL
      200.storage-object=PL stored procedures
      300.cursor=PL cursors
      400.control-statement=PL conditional control statements
      500.pl-manipulation-statement-mysql=PL data manipulation statements
      600.sql-statements-for-pl-stored-programs=PL data definition statements
      700.pl-database-management-statements=PL database management statements
      800.information-schema-dictionary-view=PL related dictionary views
      900.pl-exception-handling-statement=PL exception handling
      1000.pl-system-package=PL system packages
        9950.dbms-mview=DBMS_MVIEW
        10050.dbms-mview-stat=DBMS_MVIEW_STATS
        13200.dbms_partition=DBMS_PARTITION
        13300.dbms-resource-manager=DBMS_RESOURCE_MANAGER
        15900.dbms-stats=DBMS_STATS
        17800.dbms-udr=DBMS_UDR
        17850.dbms-vector=DBMS_VECTOR
        17900.dbms-workload-repository=DBMS_WORKLOAD_REPOSITORY
  600.error-code=Error Code
  700.telemetry=Telemetry
  900.sdk=SDK
    10.pyseekdb-sdk=pyseekdb
      30.sdk-samples=SDK samples
      50.apis=APIs
        110.database=Database
        200.collection=Collection
        300.dml=DML
        400.dql=DQL
      60.embedding-funcations=User-defined functions
500.tutorials=Tutorials
  100.create-ai-app-demo=Build AI applications
  200.scenarios=Scenarios
600.demos=Demos