100.get-started=Get started
  10.overview=seekdb 概述
  50.use-seekdb-with-sdk=使用 SDK
  100.use-seekdb-with-sql=使用 SQL
  200.ai-coding=在 AI Coding 中使用 seekdb
200.develop=Develop
  10.overview=开发概述
  50.ai-workflow=AI 工作流
  100.connect-to-seekdb=连接 seekdb
    200.use-client-connect-seekdb=通过客户端连接
    300.sample-program=示例程序
      100.java=Java
      200.python=Python
      300.c=C
      400.go=Go
      500.php=PHP
      600.rust=Rust
      700.ruby=Ruby
    400.use-the-database-connection-pool=连接池
  200.design-database-schema=数据库模式设计
    35.multi-model=多模数据
      100.json=JSON 数据
      200.spatial=空间数据
      300.char-and-text=字符和文本数据
  300.read-and-write-data=数据写入和读取
    100.write-data=写入数据
    200.read-data=读取数据
      200.multi-table-join-query=多表联合查询
      300.use-operators-and-functions-in-query=在查询中使用运算符和函数
  400.llm=接入大模型
  500.vector-embedding=向量嵌入
  600.search=搜索
    300.vector-search=向量搜索
      200.vector-index=向量索引
        300.dense-vector-index=稠密向量索引
        400.sparse-vector-index=稀疏向量索引
  700.ai-function=AI 函数服务
300.integrations=Integrations
  100.frameworks=框架
  200.model-platforms=模型平台
  300.developer-tools=编程工具
  400.workflows=工作流
  500.data-analyst=数据分析
  600.mcp=MCP
  650.plugin=插件
  700.others=其他
400.guides=Guides
  400.deploy=部署 seekdb
    500.environment-and-configuration-checks=部署前准备
    700.server-mode=服务器模式
  500.manage=管理 seekdb
    100.configuration-management=配置管理
      200.system-configuration-items=配置项
      300.system-variable=系统变量
    200.high-availability=高可用
	200.recyclebin=回收站管理
    300.security=安全权限
      200.identification-and-authentication=身份鉴别和认证
      300.access-control=访问控制
        200.user-and-permission=用户和权限
          200.permission=权限管理
            340.role-management=角色管理
      400.data-transfer-encryption=数据传输加密
  1000.obshell=运维工具 obshell
    300.obshell-clients=obshell 命令
    350.obshell-dashboard=obshell Dashboard
  1050.data-load-and-dump=数据导入导出
  1100.performance-test=性能测试
    100.vectordbbench-test-on-seekdb=seekdb Vectordbbench 测试
    200.sysbench-test-on-seekdb=seekdb Sysbench 测试
    300.tpc-h-test-on-seekdb=seekdb TPC-H 测试
    400.mldr-test-on-seekdb=seekdb MLDR 测试
  1300.release-notes=Release notes
450.reference=Reference
  100.mysql-compatibility=兼容性
  200.sql=SQL 参考
    100.sql-syntax=SQL 语法
      100.basic-elements=基本元素
        100.data-type=数据类型
          200.numeric=数值类型
          300.date-and-time-types=日期时间类型
          400.string=字符类型
          500.large-object=大对象和文本类型
          800.json-formatted-data-type=JSON 数据类型
          900.spatial-data-type=空间数据类型
          1000.roaring-bitmap-data-type=高效压缩位图数据类型
          1200.array-data-type=数组数据类型
          1300.map-data-type=映射数据类型
        200.expression=表达式
        300.character-set-and-collation=字符集与字符序
        400.literal=字面量
      200.operator=运算符
      400.functions=函数
        200.single-row-functions=单行函数
          100.date-and-time-functions=日期时间函数
          200.string-functions=字符串函数
          300.conversion-functions=转换函数
          400.mathematical-functions=数学函数
          500.comparison-functions=比较函数
          600.process-control-functions=流程控制函数
        300.aggregate-function=聚合函数
        400.analysis-functions=分析函数
        500.encryption-and-compression-functions=加密函数
        600.information-functions=信息函数
        700.json-functions=JSON 函数
          100.create-json-text-function=创建 JSON 文本的函数
          200.search-json-text-function=搜索 JSON 文本的函数
          300.modify-json-text-function=修改 JSON 文本的函数
          400.return-json-text-property-function=返回 JSON 文本属性的函数
          500.json-utility-function=JSON 工具函数
          600.json-aggregate-function=JSON 聚合函数
          700.json-schema-function=JSON Schema 验证函数
        750.xml-functions=XML 函数
          300.querying-xmltype-data-functions=查询 XML 数据的函数
          400.modify-xmltype-data-functions=修改 XML 数据的函数
        800.spatial-functions=空间函数
        900.performance-schema=Performance Schema 函数
        920.lock-functions=锁函数
        940.roaring-bitmap-functions=位图函数
        950.array-functions=数组函数
        960.text-processing-functions=文本处理函数
        970.audit-functions=审计函数
        980.map-functions=映射函数
        990.sequence-function=序列函数
        1000.other-functions=其它函数
      500.queries-and-subqueries=查询和子查询
      600.sql-statement=SQL 语句
        300.alter-system=ALTER SYSTEM
        8100.select=SELECT
      700.ddl-function=DDL 功能
      800.overview-of-pseudo-columns=伪列
    300.pl=PL 参考
      100.what-is-pl=什么是 PL
      200.storage-object=PL 存储程序
      300.cursor=PL 游标
      400.control-statement=PL 条件控制语句
      500.pl-manipulation-statement-mysql=PL 数据操作语句
      600.sql-statements-for-pl-stored-programs=PL 数据定义语句
      700.pl-database-management-statements=PL 数据库管理语句
      800.information-schema-dictionary-view=PL 相关字典视图
      900.pl-exception-handling-statement=PL 异常处理
      1000.pl-system-package=PL 系统包
        10050.dbms-mview-stat=BMS_MVIEW_STATS 概述
        13200.dbms_partition=DBMS_PARTITION 概述
        17900.dbms-workload-repository=DBMS_WORKLOAD_REPOSITORY 概述
        15900.dbms-stats=DBMS_STATS 概述
        17850.dbms-vector=DBMS_VECTOR 概述
        13300.dbms-resource-manager=DBMS_RESOURCE_MANAGER 概述
        9950.dbms-mview=DBMS_MVIEW 概述
        17800.dbms-udr=DBMS_UDR 概述
  600.error-code=常用错误码
  700.telemetry=遥测
  900.sdk=SDK
    10.pyseekdb-sdk=pyseekdb
      30.sdk-samples=SDK 示例
      50.apis=APIs
        110.database=Database
        200.collection=Collection
        300.dml=DML
        400.dql=DQL
      60.embedding-funcations=自定义函数
500.tutorials=Tutorials
  100.create-ai-app-demo=搭建 AI 应用
  200.scenarios=场景实践
600.demos=Demos
